# Generated by Django 2.0.4 on 2018-04-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_printer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('productCategoryID', models.CharField(max_length=255)),
                ('printerID', models.CharField(max_length=255)),
                ('isVat', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
