# Generated by Django 2.0.4 on 2018-05-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180510_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='temprestaurantordersummary',
            name='isVat',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='temprestaurantorderdetail',
            name='isVat',
            field=models.BooleanField(default=True),
        ),
    ]
