# Generated by Django 2.0.4 on 2018-05-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180510_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='temprestaurantordersummary',
            name='isVat',
            field=models.BooleanField(default=True),
        ),
    ]
