# Generated by Django 2.0.4 on 2018-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180503_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTransactionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountCode', models.CharField(blank=True, max_length=255, null=True)),
                ('branchCode', models.CharField(blank=True, max_length=255, null=True)),
                ('userID', models.CharField(blank=True, max_length=255, null=True)),
                ('beginningCash', models.DecimalField(decimal_places=2, max_digits=8)),
                ('beginningInvoice', models.CharField(blank=True, max_length=255, null=True)),
                ('beginningOR', models.CharField(blank=True, max_length=255, null=True)),
                ('lastOR', models.CharField(blank=True, max_length=255, null=True)),
                ('lastTransactionNo', models.CharField(blank=True, max_length=255, null=True)),
                ('nextBeginningCash', models.DecimalField(decimal_places=2, max_digits=8)),
                ('noOfSoldItem', models.IntegerField()),
                ('totalSoldItem', models.IntegerField()),
                ('noOfCancelledItem', models.IntegerField()),
                ('totalCancelledItem', models.IntegerField()),
                ('totalSales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalCashSales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('totalCash', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cashRemitted', models.DecimalField(decimal_places=2, max_digits=8)),
                ('openBy', models.CharField(blank=True, max_length=255, null=True)),
                ('closedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('shortage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('isVat', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
