# Generated by Django 2.0.4 on 2018-05-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_salestransactionsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sellingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='cashRemitted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='nextBeginningCash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='noOfCancelledItem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='noOfSoldItem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='shortage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='totalCancelledItem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='totalCash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='totalCashSales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='totalSales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='totalSoldItem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
