# Generated by Django 2.0.4 on 2018-05-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180511_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temprestaurantorderdetail',
            old_name='qytSold',
            new_name='qtySold',
        ),
    ]
