# Generated by Django 2.0.4 on 2018-05-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_restaurantorderdetail_restaurantordersummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantordersummary',
            name='discountType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='isErrorCorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='isHold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='isVoid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='paymentType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='seniorControlNo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='seniorName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='totalCharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='totalDiscount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='totalItemCancelled',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='totalUnitPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
