# Generated by Django 2.0.4 on 2018-05-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180523_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransactionsummary',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
