# Generated by Django 2.0.4 on 2018-05-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_salestransactionsummary_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='noOfCancelledItem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='noOfSoldItem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='totalCancelledItem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='salestransactionsummary',
            name='totalSoldItem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
