# Generated by Django 2.0.4 on 2018-05-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180523_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='isVat',
            field=models.BooleanField(default=True),
        ),
    ]
