# Generated by Django 2.0.4 on 2018-05-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180525_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantordersummary',
            name='totalItemVoid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
