# Generated by Django 2.0.4 on 2018-05-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_restaurantordersummary_totalitemvoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantorderdetail',
            name='isVat',
            field=models.BooleanField(default=False),
        ),
    ]
