# Generated by Django 2.0.4 on 2018-05-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180528_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantordersummary',
            name='cancelledBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='holdBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='isCancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='isConfirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantordersummary',
            name='voidBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
