# Generated by Django 2.0.4 on 2018-06-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180528_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiterCode', models.CharField(blank=True, max_length=255, null=True)),
                ('waiterName', models.CharField(blank=True, max_length=255, null=True)),
                ('isVat', models.BooleanField(default=False)),
                ('addedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
